version: '3.8'  # Adjust if using a different docker-compose version

volumes:
  postgres-data:

services:
  db:
    container_name: postgres
    image: postgres:latest  # Or a specific version like postgres:14

    environment:
      POSTGRES_USER: ims_user  # Replace with your desired username
      POSTGRES_PASSWORD: ims_password  # Replace with your desired password
      POSTGRES_DB: ims_db  # Replace with your desired database name

    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for database

    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432

    restart: unless-stopped  # Restart container automatically unless manually stopped

    # Optional healthcheck (recommended)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s  # Check every 30 seconds
      timeout: 10s  # Fail if check takes longer than 10 seconds
      retries: 5  # Retry up to 5 times before considering unhealthy

  app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ims_db
      - SPRING_DATASOURCE_USERNAME=ims_user
      - SPRING_DATASOURCE_PASSWORD=ims_password
