server:
  port: 5002

spring:
  application:
    name: ims-service
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    page-size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/ims_db
    username: ims_user
    password: ims_password

product:
  max-allowed-images: 2

